### ISSUE TITLE
game wont launch after removing vein mining mod

### ISSUE THREAD

**Issue by memphismc** [illusivesoulworks/spectrelib#7] opened 2024-03-06 13:09 UTC
[crash-2024-03-06_15.08.45-client.txt](https://github.com/illusivesoulworks/spectrelib/files/14510265/crash-2024-03-06_15.08.45-client.txt)

**Comment by TheIllusiveC4** [comment] 2024-03-06 19:31
Duplicate of https://github.com/illusivesoulworks/spectrelib/issues/3
BetterDays is packaging an old version of SpectreLib that is incompatible with your Fabric Loader version. Either downgrade your Fabric Loader to 0.14.22 or below, update SpectreLib with the 0.13.14+1.20.1 release on [GitHub releases](https://github.com/illusivesoulworks/spectrelib/releases/tag/v0.13.14%2B1.20.1), or remove BetterDays.

**Closed by TheIllusiveC4** 2024-03-06 19:31 UTC
Labels: bug, duplicate
