### ISSUE TITLE
Not compatible with fabric 0.14.23

### ISSUE THREAD

**Issue by slovinsqui** [illusivesoulworks/spectrelib#5] opened 2023-10-13 02:59 UTC
exaroton server hosting does not let me downgrade fabric loader versions, and Im stuck with 0.14.23 wich does not let me run the server

**Comment by TheIllusiveC4** [comment] 2023-10-13 07:48
Duplicate of https://github.com/illusivesoulworks/spectrelib/issues/3
If you cannot downgrade the loader for some reason, then you'll need to wait until I release the mods with the updated version (which I'm in the process of doing right now).

**Closed as not planned** 2023-10-13 07:48 UTC
Labels: bug, duplicate

**Comment by slovinsqui** [comment] 2023-10-17 01:39
I tried to uninstall charm of undying alongside specterlib so I could start my server while the update is uploaded, but I can´t find it in the mods folder, is it located somewhere else?

nvm, I forgot I had other mods that kept the library installed lol
